UPDATE desk_color
SET color_code = CASE color_meaning
    WHEN 'AVAILABLE' THEN '#10b981'
    WHEN 'FULLY BOOKED' THEN '#ef4444'
    WHEN 'PARTIALLY BOOKED' THEN '#f59e0b'
    WHEN 'ASSIGNED' THEN '#3b82f6'
    WHEN 'UNAVAILABLE' THEN '#6b7280'
    WHEN 'MY BOOKINGS' THEN '#8b5cf6'
    ELSE color_code
END
WHERE color_meaning IN ('AVAILABLE', 'FULLY BOOKED', 'PARTIALLY BOOKED', 'ASSIGNED', 'UNAVAILABLE', 'MY BOOKINGS');
